<a href="https://colab.research.google.com/github/Buenobarbie/Working-with-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors
### Creating Tensors


In [4]:
# szeroscalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0][0]

tensor([1, 2, 3])

In [20]:
# Interacting with tensors
TENSOR2 = torch.tensor([[[1,2,3,4],
                        [0,7,3,8],
                        [4,4,9,0]],

                       [[1,2,3,4],
                        [0,7,3,8],
                        [4,4,9,0]],])
TENSOR2

tensor([[[1, 2, 3, 4],
         [0, 7, 3, 8],
         [4, 4, 9, 0]],

        [[1, 2, 3, 4],
         [0, 7, 3, 8],
         [4, 4, 9, 0]]])

In [21]:
TENSOR2.shape

torch.Size([2, 3, 4])

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [22]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3701, 0.5080, 0.9381, 0.9116],
        [0.6095, 0.7983, 0.0260, 0.9120],
        [0.5566, 0.1701, 0.4738, 0.3267]])

In [23]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
random_image_size_tensor[0][0] # Represents the rgb value of pixel x=0 y=0

tensor([0.3699, 0.1140, 0.0437])

In [25]:
# Create a random tensor with similar shape to an image tensor per RGB

random_image_size_tensor2 = torch.rand(size=(3,224,224)) #color channels (R,G,B), height, width
random_image_size_tensor2.shape, random_image_size_tensor2.ndim

(torch.Size([3, 224, 224]), 3)

In [26]:
random_image_size_tensor2[0] # Represents the value of Red for each pixel in the image

tensor([[0.1748, 0.0376, 0.1150,  ..., 0.1421, 0.9914, 0.6263],
        [0.3054, 0.8730, 0.6204,  ..., 0.5548, 0.3844, 0.5609],
        [0.7973, 0.9996, 0.1783,  ..., 0.4442, 0.5049, 0.4630],
        ...,
        [0.8438, 0.9529, 0.3640,  ..., 0.0770, 0.6479, 0.4930],
        [0.5358, 0.7799, 0.6678,  ..., 0.4482, 0.0836, 0.4399],
        [0.7818, 0.6170, 0.9883,  ..., 0.4314, 0.8220, 0.6071]])

## Zeros and Ones

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all zeros
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [29]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
range_tensor = torch.arange(start=0, end=1001, step=100)
range_tensor

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [31]:
# Crating tensors like (copying shape)
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with tensors operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [33]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
int_32_tensor.size()

torch.Size([3])

**Note** : 3 Big errors you might run into with PyTorch & deep leraning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

### Manioulating Tensors

Tensors operations include:
- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication



In [37]:
# Add 10 to tensor
a_tensor = torch.tensor([1,2,3])
a_tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
a_tensor * 10 # torch..mul(a_tensor, 10)

tensor([10, 20, 30])

In [39]:
# Subtract 10 from tensor
a_tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

In [40]:
# Element wise multiplication
print(a_tensor, "*", a_tensor)
a_tensor * a_tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(a_tensor, a_tensor)

tensor(14)

In [42]:
a_tensor @ a_tensor

tensor(14)

In [44]:
# Only multiply matrices
matrix_A = torch.rand(2,3)
matrix_B = torch.rand(3,2)
torch.mm(matrix_A, matrix_B)

tensor([[1.8985, 1.3696],
        [0.6329, 0.5244]])

In [47]:
# Transpose
matrix_C = torch.rand(2,3)
matrix_C

tensor([[0.9798, 0.7678, 0.3893],
        [0.2730, 0.9253, 0.3175]])

In [48]:
matrix_C.T

tensor([[0.9798, 0.2730],
        [0.7678, 0.9253],
        [0.3893, 0.3175]])

## Finding the min, max, mean, sum, etc (tensor agregation)


In [49]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [51]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
# torch.mean() requires a tensor of float datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding positional min and max

In [59]:
x.argmin()

tensor(0)

In [60]:
y = torch.rand(2,3)
y

tensor([[0.3529, 0.3556, 0.0821],
        [0.4227, 0.4209, 0.3229]])

In [61]:
y.min(), y.argmin()

(tensor(0.0821), tensor(2))

## Reshaping, stacking, squeezing and unsqueezing
- Reshaping - reshapes an input tensor to a defined shape
- view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tesnors on top of each other (vstack) or side by side (hstack)
- Squeeze - remove all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [63]:
# Crate a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

In [64]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
# Stack tensors on top of each other
z[:,0] = 1
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [73]:
# Stack tensors next to each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [75]:
# Squeezing
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
# Unsqueezing
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [84]:
x_unsqueezed = x_unsqueezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[1.]],
 
         [[2.]],
 
         [[3.]],
 
         [[4.]],
 
         [[5.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1, 1]))

In [87]:
# Permuting
# (Returns a view = shares memory)
x_original = torch.rand((224,224,3)) # height, width, colour_channels
x_original.shape

torch.Size([224, 224, 3])

In [88]:
# Permute to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # colour_channels, width, height
x_permuted.shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [89]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
# Indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
x[0,0] # x[0][0]

tensor([1, 2, 3])

In [93]:
x[0,0,0]

tensor(1)

In [96]:
x[:,:,1]

tensor([[2, 5, 8]])

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionalitu to interacrt with it.

- Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

```
# This is formatted as code
```



In [98]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [99]:
# Warning: The data type is now float64
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [100]:
# Tensor to Numpy
tensor = torch.ones(7)
# Warning: The data type is now float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to make random out of random)

To reduce the randomness comes the concept of a ***random seed***.


In [103]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [106]:
# Create two pseudo-random tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs
GPUs = faster computation on numbers

### Getting a GPU
 - Use Google Colab
 - Use your own GPU: Tim Dettmers - Which GPUs to get for deep learning
 - Use cloud computing

 For the last two PyTorch needs a setting up

## Check for GPU acess with PyTorch

In [108]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [109]:
import torch
torch.cuda.is_available()

False

In [110]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [111]:
# Count number of devices
torch.cuda.device_count()

0

Putting tensors and models on the GPU

In [112]:
# Create a tensor (default is on the cpu)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [114]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

If tensor is on GPU, can't transform it to NumPy
We can first set it to the CPU

In [117]:
tensor_cpu = tensor_on_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])

## Questions
- How to create a random tensor of dimension 0?




## Extracurricular
- PyTorch Reproducibility